version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env 
    depends_on:
      - redis
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  auth:
    build: ./auth
    ports:
      - "5001:5000"
    depends_on:
      postgres: 
        condition: service_healthy
    env_file:
      - .env 

  api:
    build: ./api
    ports:
      - "5002:5000"
    depends_on:
      - redis
    
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - auth
      - api
  
volumes:
  pgdata:
