apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_DB
          value: admin
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: admin
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "nc -z -w 10 postgres 5432"
          initialDelaySeconds: 50
          periodSeconds: 20
