apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  ports:
    - port: 10250
      targetPort: 10250
      protocol: TCP
  selector:
    k8s-app: metrics-server
  type: ClusterIP
